- src/sound.js
small tweak i had on branch before fixing memory leak
> support swapping songs via number keys

- package.json
- src/sound.js
- yarn.lock
Substantive change here is just package.json, not sure if we're outdated for a reason or no. I merged #31 into this to show the tweaks it allows, so merge that first for a cleaner diff.
> Bump linter

- src/anybody.js
- src/visuals.js
A little chore as I was looking at drawing perf. With the memory fix I'm seeing no slowdown, my comp maxes out around 230fps.
> fix: fps gauge just looks at the last n frames

- src/q5.js
> fix: one more mobile error

- src/sound.js
- test/solver.test.js
this fixes the test breakages you found, @okwme
> fix solver test by checking for window

- src/visuals.js
part of #59 
png face style next
> refactor drawBody and drawBodyTrails to support face, body, tail style

- src/anybody.js
- src/nft.js
- src/visuals.js
> small face change

- src/anybody.js
- src/visuals.js
Ended up making a button in p5. I think this is OK since there are just not ever going to be many buttons to check on screen.
Also added anybody.ownerPresent to hide the button in the case that we're in the frontend.
> Success style button

- src/sound.js
> use prando to deterministically choose song from seed

- src/visuals.js
> do not draw gridline or gun on pixel 0

- server/src/leaderboard.ts
This adds `leaderboard.allTime.daysPlayed` as discussed in https://github.com/trifle-labs/anybody-problem-frontend/pull/66
I also tweaked most solved to be most solutions. I think this could be a cool and high scoring variation or we can remove if its spammy.
> add most days played to leaderboard result

- src/anybody.js
i find it preferable while playing on touchpad, where after aiming you have to lift your finger to shoot
made "p" key pause
> shoot with spacebar, pause with P

- server/shovel-config.ts
- server/shovel.test.ts
- server/src/index.ts
- server/src/leaderboard.ts
Fixes up the queries and shovel code for the new schema. Not sure it's 100 but at least close and we'll confirm w more data.
> Speedrun leaderboard

- src/anybody.js
- src/nft.js
- src/visuals.js
- tweaked some conflicts with r and p button during game over screen
- tracking level scores to show an end game
- allows option of best times to compare, otherwise just shows your own best
- make date correct on final screen
- show this.owner for name
- shortened celebrationTime
- allow you to click or press button to skip celebration time
- added button and logic to prevent going past level 5 and allow submitting score (ok to just `anybody.readyToSave = true` in front end?)
- made faces on pause screen show up with normal face and blink every 5 seconds
- added back the edge loop except for the part that matters when aiming
> Button entrance billy

- src/anybody.js
- src/visuals.js
needs to be added to frontend to take effect
> fix broken gun bug

- package.json
- src/anybody.js
- src/colors.js
- src/sound.js
- src/visuals.js
- yarn.lock
actually some more cleanup after #212 no longer need prando at all.
also some tweaks to sounds so that it's a different song per level
> remove unnecessary old color and random stuff

- server/src/index.ts
- server/src/leaderboard.ts
- server/src/wallet.ts
https://github.com/trifle-labs/anybody-problem/issues/205
> API upgrades

- server/src/leaderboard.ts
I ended up just including today's level times in the JSON payload because it significantly increases payload size to include for all (~6kb -> ~18kb). However, I did the query in the daily and left a 1 line switch to start including it for all dailies.
As a smoke test, here are the level times from today:
And the JSON from the API
```
{
"leaderboard": {
"daily": {
"1720224000": {
"levels": [],
"cumulative": []
},
"1720310400": {
"levels": [],
"cumulative": [
{
"runId": 2,
"day": 1720310400,
"date": "2024-07-07",
"time": 1371,
"player": "0xfa398d672936dcf428116f687244034961545d91"
}
]
},
"1720396800": {
"levels": [],
"cumulative": [
{
"runId": 3,
"day": 1720396800,
"date": "2024-07-08",
"time": 808,
"player": "0xfa398d672936dcf428116f687244034961545d91"
}
]
},
"1720483200": {
"levels": [], …
```
> fix leaderboard api: include best level times for today

- src/anybody.js
- src/buttons.js
- src/colors.js
- src/visuals.js
Show connect wallet modal inside game if a `playerName` has not been passed into the game.
part of #198
> feat: connect-wallet popup

- src/visuals.js
closes #164 
(TODO: hide buttons, paint some sort of promo message?)
> feat: share/copy-clipboard win screen as PNG

- src/anybody.js
- src/sound.js
- src/visuals.js
- mute on 'M'
- gameover music
- refactor
> Audio refactor 2
